print("--WELCOME TO CAlCULATOR--")
print("Please type first number")
x = int(input())
print("Please type second number")
y = int(input())
print("--RESULTS--")
print("x + y =" , x + y)
print("x - y =" , x - y)
print("x * y =" , x * y)
print("x / y =" , x / y)